
import { jsPDF } from 'jspdf';

/**
 * Loads the NaNumMyeongjo font from the public directory and adds it to the jsPDF instance.
 */
async function loadFont(doc: jsPDF) {
    try {
        const response = await fetch('/fonts/NanumMyeongjo.ttf');
        if (!response.ok) throw new Error('Failed to load font');
        const buffer = await response.arrayBuffer();

        // Convert ArrayBuffer to binary string
        let binary = '';
        const bytes = new Uint8Array(buffer);
        const len = bytes.byteLength;
        for (let i = 0; i < len; i++) {
            binary += String.fromCharCode(bytes[i]);
        }

        // Add font to VFS and register it
        doc.addFileToVFS('NanumMyeongjo.ttf', btoa(binary));
        doc.addFont('NanumMyeongjo.ttf', 'NanumMyeongjo', 'normal');
        doc.setFont('NanumMyeongjo');
    } catch (e) {
        console.error("Font loading failed, falling back to default", e);
    }
}

export async function generateBookPDF(
    script: string,
    targetPages: number, // Kept for interface compatibility but not used for expansion
    options: { title?: string, coverStyle?: string } = {}
) {
    const doc = new jsPDF();
    const { title = "나의 시나리오", coverStyle = "Classic" } = options;

    // 1. Load Font
    await loadFont(doc);

    // 2. Cover Page
    let coverBg = [20, 20, 20]; // Default Dark (Cinema Style)
    let textColor = [255, 255, 255]; // White

    if (coverStyle === 'Modern') {
        coverBg = [255, 255, 255];
        textColor = [0, 0, 0];
    } else if (coverStyle === 'Artistic') {
        coverBg = [212, 175, 55];
        textColor = [26, 60, 52];
    }

    doc.setFillColor(coverBg[0], coverBg[1], coverBg[2]);
    doc.rect(0, 0, 210, 297, 'F');

    doc.setTextColor(textColor[0], textColor[1], textColor[2]);
    doc.setFontSize(24);
    doc.text("SCREENPLAY", 105, 80, { align: 'center' });

    doc.setFontSize(40);
    doc.text(title, 105, 120, { align: 'center' });

    doc.setFontSize(14);
    doc.text("Generated by Cosmic Writer AI", 105, 140, { align: 'center' });

    // 3. Content Pages
    doc.addPage();
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);

    const lines = doc.splitTextToSize(script, 165);
    let y = 30;
    const pageHeight = 280;

    for (let i = 0; i < lines.length; i++) {
        if (y > pageHeight) {
            doc.addPage();
            y = 30;
        }

        // Simple heuristic for formatting check (e.g. Center character names)
        const line = lines[i];
        if (line.match(/^[A-Z0-9 ]+$/) && !line.startsWith('EXT.') && !line.startsWith('INT.')) {
            // Character Name (All Caps, not Scene Heading) - rough guess
            doc.text(line, 80, y); // Indent for character
        } else if (line.trim().startsWith('(')) {
            doc.text(line, 70, y); // Parenthetical
        } else {
            doc.text(line, 20, y); // Action / Dialogue / Sluglines
        }

        y += 7;
    }

    // Save
    const fileName = title.replace(/\s+/g, '_').slice(0, 20);
    doc.save(`${fileName}_Scenario.pdf`);
    return true;
}
